# Red/Black kitty theme

foreground         #e0e0e0
background         #0a0404
cursor             #e0e0e0

active_tab_foreground     #ffffff
active_tab_background     #aa3333
inactive_tab_foreground   #aa3333
inactive_tab_background   #0a0000

active_border_color   #aa3333
inactive_border_color #000000
bell_border_color     #ff0000

# Black
color0      #1a1a1a
color8      #4d4d4d

# Red
color1      #aa3333
color9      #cc4444

# Green
color2      #33aa33
color10     #44cc44

# Yellow
color3      #aa8833
color11     #ccaa44

# Blue
color4      #3333aa
color12     #4444cc

# Magenta
color5      #aa3366
color13     #cc4488

# Cyan
color6      #339999
color14     #44bbbb

# White
color7      #cccccc
color15     #ffffff
