# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# Commands and Apps to be executed at launch

# Wallpaper
exec-once = sleep 1 && swww img ~/wallpaper.jpg

# Autostart apps
exec-once = brave-browser
exec-once = code
exec-once = spotify
