# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# Commands and Apps to be executed at launch

# Wallpaper
exec-once = sleep 1 && swww img ~/wallpaper.jpg

# Focus main monitor and workspace 1 before launching apps
exec-once = hyprctl dispatch focusmonitor DP-1 && hyprctl dispatch workspace 1

# Autostart apps
exec-once = sleep 1 && brave-browser
exec-once = sleep 1 && code
exec-once = sleep 2 && spotify

# Ensure workspace 1 stays focused on main monitor after apps launch
exec-once = sleep 5 && hyprctl dispatch focusmonitor DP-1 && hyprctl dispatch workspace 1
