# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# User Settings
# This is where you put your own settings as this will not be touched during update 
# if the upgrade.sh is used.

# refer to Hyprland wiki for more info https://wiki.hyprland.org/Configuring/Variables/
# NOTE: some settings are in ~/.config/hypr/UserConfigs/UserDecorAnimations.conf
#
# Look on ~/.config/hypr/configs/SystemSettings.conf to know how to modify this

input {
    follow_mouse = 2
    kb_layout = us,es
    kb_variant = altgr-intl,
}

decoration {
    rounding = 0
    dim_inactive = true
    dim_strength = 0.4
}

general {
    gaps_in = 1
    gaps_out = 0
    border_size = 2
    col.active_border = rgb(aa3333)
    col.inactive_border = rgb(000000)
}

binds {
    workspace_back_and_forth = false
}
