# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules
# This file will not be modified during dotfiles updates

# Assign apps to workspaces
windowrule {
    name = Brave
    match:class = ^(Brave-browser)$
    workspace = 1
}
windowrule {
    name = VSCode
    match:class = ^(Code)$
    workspace = 3
}
windowrule {
    name = Spotify
    match:class = ^(Spotify)$
    workspace = 5
}
