[General]
#################### General ####################

ScreenWidth=""
ScreenHeight=""
ScreenPadding=""

Font="JetBrainsMono Nerd Font"
FontSize="13"

KeyboardSize="0.4"

RoundCorners="0"

Locale=""
HourFormat="HH:mm:ss"
DateFormat="dddd d MMMM"

HeaderText=""

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/wallpaper.jpg"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.5"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

HeaderTextColor="#aa3333"
DateTextColor="#aa3333"
TimeTextColor="#ffffff"

FormBackgroundColor="#000000"
BackgroundColor="#000000"
DimBackgroundColor="#000000"

LoginFieldBackgroundColor="#0a0000"
PasswordFieldBackgroundColor="#0a0000"
LoginFieldTextColor="#aa3333"
PasswordFieldTextColor="#ffffff"
UserIconColor="#aa3333"
PasswordIconColor="#aa3333"

PlaceholderTextColor="#662222"
WarningColor="#ff0000"

LoginButtonTextColor="#ffffff"
LoginButtonBackgroundColor="#aa3333"
SystemButtonsIconsColor="#aa3333"
SessionButtonTextColor="#aa3333"
VirtualKeyboardButtonTextColor="#aa3333"

DropdownTextColor="#ffffff"
DropdownSelectedBackgroundColor="#aa3333"
DropdownBackgroundColor="#0a0000"

HighlightTextColor="#ffffff"
HighlightBackgroundColor="#aa3333"
HighlightBorderColor="#aa3333"

HoverUserIconColor="#ffffff"
HoverPasswordIconColor="#ffffff"
HoverSystemButtonsIconsColor="#ffffff"
HoverSessionButtonTextColor="#ffffff"
HoverVirtualKeyboardButtonTextColor="#ffffff"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="32"
Blur=""

HaveFormBackground="true"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="true"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
